name: Create RunPod CPU Pod

on:
  workflow_dispatch:
  schedule:
    - cron: '5 */2 * * *' # Every 2 hours at minute 5

jobs:
  create:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Create Pod from Template
        id: create_pod
        run: |
          RESPONSE=$(curl -s -X POST https://rest.runpod.io/v1/pods \
            -H "Authorization: Bearer ${{ secrets.RUNPOD_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "templateId": "${{ secrets.RUNPOD_OSS_CAPTAIN_TEMPLATE_ID }}"
            }')

          echo "API Response: $RESPONSE"
          
          POD_ID=$(echo "$RESPONSE" | jq -r '.id')

          if [ "$POD_ID" = "null" ] || [ -z "$POD_ID" ]; then
            echo "❌ Failed to create pod."
            exit 1
          fi

          echo "✅ Created Pod ID: $POD_ID"
          echo "pod_id=$POD_ID" >> $GITHUB_OUTPUT
